#pragma once
#include "sdkconfig.h"

#define ENABLED  (1)
#define DISABLED (0)

//Bridge values from sdkconfig 

#define MAX_UNIVERSAL_OBJ_INSTANCES        8096

#ifdef CONFIG_UCANVAS_USE_PPA_FOR_RENDERING
#define USE_PPA_FOR_RENDERING              (CONFIG_UCANVAS_USE_PPA_FOR_RENDERING ? ENABLED : DISABLED)
#else 
#define USE_PPA_FOR_RENDERING DISABLED
#endif
#define UCANVAS_USE_SPIRAM                 (CONFIG_UCANVAS_USE_SPIRAM ? ENABLED : DISABLED)

#define UCANVAS_TASK_STACK_SIZE            CONFIG_UCANVAS_TASK_STACK_SIZE
#define UCANVAS_RENDER_TASK_STACK_SIZE     CONFIG_UCANVAS_RENDER_TASK_STACK_SIZE
#define UCANVAS_RENDER_TASK_PRIORITY       CONFIG_UCANVAS_RENDER_TASK_PRIORITY

#define UCANVAS_TEXTBOX_MAX_CONTNENT_SIZE  CONFIG_UCANVAS_TEXTBOX_MAX_CONTENT_SIZE

#define UCANVAS_DEFAULT_RED                CONFIG_UCANVAS_DEFAULT_RED
#define UCANVAS_DEFAULT_GREEN              CONFIG_UCANVAS_DEFAULT_GREEN
#define UCANVAS_DEFAULT_BLUE               CONFIG_UCANVAS_DEFAULT_BLUE

#define UCANVAS_USE_DOUBLE_BUFFERING       (CONFIG_UCANVAS_USE_DOUBLE_BUFFERING ? ENABLED : DISABLED)
#define UCANVAS_DIRTY_RECT_FALLBACK_FULL_PCT 50